### PR TITLE
Package-loading robustness fixes

### PR DESCRIPTION
**Pull request by ckreibich**
Hi folks! There's currently a subtle problem with your Zeek ICS packages: when you install these via `zkg` and also leave package loads up to the `packages.zeek` file maintained by `zkg`, then the layout of your Zeek scripts folder causes all script files to get loaded twice, which Zeek cannot handle and makes it error out. That's because Zeek once installs them as part of the plugin that your package provides, and once as a "regular" Zeek package because of the `script_dir` entry in your `zkg.meta`.

Here's an example of what this looks like — I have the bacnet package installed and loaded:
```
$ zkg list
/home/christian/devel/zeek/packages/amzn/zeek-plugin-bacnet (installed: master) - Plugin that enables parsing of the BACnet standard building controls protocol
```
```
$ zeek -NN
...
Zeek::BACnet - BACnet protocol analyzer (dynamic, no version information)
    [Analyzer] BACnet (ANALYZER_BACNET, enabled)
    [Event] bacnet
```
When I now run `zeek`, e.g. to process a pcap as usual, then all is fine:
```
$ zeek -r http.pcap
$
```
But when I include the packages.zeek file that `zkg` maintains ...
```
$ cat $(zeek-config --script_dir)/site/packages/packages.zeek
# WARNING: This file is managed by zkg.
# Do not make direct modifications here.
@load ./zeek-plugin-bacnet
```
... then things break:
```
$ zeek -r http.pcap packages
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 8 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 9: redefinition requires "redef" (BACnet::bvlc_functions)
error in /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 23: Duplicate &default attribute is ambiguous
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 26 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 27: redefinition requires "redef" (BACnet::ipv6_bvlc_functions)
error in /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 41: Duplicate &default attribute is ambiguous
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 44 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 45: redefinition requires "redef" (BACnet::apdu_types)
error in /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 53: Duplicate &default attribute is ambiguous
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 56 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 57: redefinition requires "redef" (BACnet::confirmed_services)
error in /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 88: Duplicate &default attribute is ambiguous
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 91 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 92: redefinition requires "redef" (BACnet::unconfirmed_services)
error in /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 104: Duplicate &default attribute is ambiguous
warning in /home/christian/inst/opt/zeek/lib64/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./consts.zeek, line 107 and /home/christian/inst/opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./consts.zeek, line 108: redefinition requires "redef" (BACnet::results)
...
```
The way to avoid this is by separating scripts that are meant for plugin context only (e.g. to provide script-layer types that the plugin needs) from scripts that provide the "usual" logging routines etc.

This PR does exactly that — it moves the script to a subdirectory of `scripts/` and updates `zkg.meta` accordingly. You could then still use e.g. `scripts/__preload__.zeek` in the future if your plugin ends up needing that. This subdirectory layout mirrors the structure we put in place when you use the `init-plugin` templating tool provided in the Zeek sources, but it's a really obscure problem. Your plugins are all awesome so I figured I'd just send PRs. We're looking into ways to make this less error-prone in the future.

Please double-check that none of the script-layer contents (e.g from `consts.zeek`) are actually needed by the analyzer at startup ... I don't think they do, but you know the implementation much better. Thanks!

*Issue #, if available:*

*Description of changes:*

(see above)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by voteblake** [comment]
Thank you so much for taking a look into this Christian! It has been reported several times (#6, #28), and I had been able to replicate/confirm but not diagnose and fix the issue. I will look to merge these after quick testing against our internal builds on Monday.

**Comment by voteblake** [comment]
Looks great, thank you again. Out of an abundance of caution I'm going to create tagged releases of the current versions before merging this so folks have a fall back option if this fix breaks any work arounds they've been using. I'll then tag a new release after merging so it will be available with the fix on `packages.zeek.org`.

**Comment by ckreibich** [comment]
Yes thank you Blake, tags are good!

**Comment by voteblake** [comment]
All five should be merged and tagged in a release to be picked up by the next update to `packages.zeek.org`

**Comment by ckreibich** [comment]
Awesome, thanks a bunch!

**Pull request merged**
